phishin-list-shows: add -R option for printing a random show

diff --git a/bin/phishin-list-shows b/bin/phishin-list-shows
--- a/bin/phishin-list-shows
+++ b/bin/phishin-list-shows
@@ -8,11 +8,13 @@ usage() {
 
     cat >&2 <<EOF
 usage: ${0##*/} [-l]
+       ${0##*/} [-R]
 
 List show dates performed by Phish, as catalogued by Phish.in.
 
 options:
-    -l              List shows liked by your user.
+    -R              List just one random show.
+    -l              List shows liked by your authenticated user.
 
 see also: phishin-like-show
 
@@ -40,10 +42,12 @@ fetch_shows_page() {
 set -euo pipefail
 
 user_agent='phish-cli <kylie@somas.is>'
+mode=list
 liked_by_user=false
-while getopts :l opt >/dev/null 2>&1; do
+while getopts :Rl opt >/dev/null 2>&1; do
     case "$opt" in
         l) liked_by_user=true ;;
+        R) mode=one_random_show ;;
         *) usage 'error: unknown command: %s\n' "${opt}" ;;
     esac
 done
@@ -52,17 +56,24 @@ shift $((OPTIND - 1))
 PHISHIN_USER_TOKEN=$(phishin-auth-login)
 export PHISHIN_USER_TOKEN
 
+case "$mode" in
+    list)
+        i=0
+        pages=("$(fetch_shows_page 1)")
+        total_pages=$(jq -cre '.total_pages' <<<"${pages[0]}")
+        for i in $(seq 2 "${total_pages}"); do
+            if ! page=$(fetch_shows_page "${i}") || [[ -z "${page}" ]]; then
+                printf 'error getting shows (page %i/%i): %s\n' \
+                    "${i}" "${total_pages}" "${page}" >&2
+                exit 1
+            fi
+            pages+=("${page}")
+        done
 
-pages=("$(fetch_shows_page 1)")
-total_pages=$(jq -cre '.total_pages' <<<"${pages[0]}")
-i=0
-for i in $(seq 2 "${total_pages}"); do
-    if ! page=$(fetch_shows_page "${i}") || [[ -z "${page}" ]]; then
-        printf 'error getting shows (page %i/%i): %s\n' \
-            "${i}" "${total_pages}" "${page}" >&2
-        exit 1
-    fi
-    pages+=("${page}")
-done
-
-jq -cr '.shows[].date' <<<"${pages[*]}"
+        jq -cr '.shows[].date' <<<"${pages[*]}"
+        ;;
+    one_random_show)
+        curl --fail-with-body "https://phish.in/api/v2/shows/random" \
+            | jq -r '.date'
+        ;;
+esac
