phish-cli: consistently use $show_date

diff --git a/bin/phish-download-show b/bin/phish-download-show
--- a/bin/phish-download-show
+++ b/bin/phish-download-show
@@ -95,7 +95,7 @@ shift $((OPTIND - 1))
 [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] \
     || usage 'error: invalid show argument format (YYYY-MM-DD required)\n'
 
-show="$1"
+show_date="$1"
 shift
 
 # Request that Phish.in generate a ZIP archive of the album, polling until it
@@ -103,7 +103,7 @@ shift
 _said=false
 while :; do
     request_album_zip=$(
-        jq -nc '{date:$show}' --arg show "$show" \
+        jq -nc '{date:$show_date}' --arg show_date "$show_date" \
             | curl --no-progress-meter --json @- \
                 'https://phish.in/api/v2/shows/request_album_zip'
     )
@@ -121,8 +121,8 @@ while :; do
 done
 
 # shellcheck disable=SC2310
-if ! phishin_show_data=$(curl --no-progress-meter --fail "https://phish.in/api/v2/shows/$show"); then
-    printf 'error: failed to download show data for %s\n' "${show}" >&2
+if ! phishin_show_data=$(curl --no-progress-meter --fail "https://phish.in/api/v2/shows/$show_date"); then
+    printf 'error: failed to download show data for %s\n' "${show_date}" >&2
     exit 1
 fi
 
@@ -177,7 +177,7 @@ if
         && ! cmp -s <(jq -c <<<"${phishin_show_data}" || printf '{}') <(jq -c <<<"${near_show_data}" || printf '{}')
 then
     # and if none of this is true, then we don't need to do anything!
-    printf '%s: downloaded version is up to date\n' "${show}" >&2
+    printf '%s: downloaded version is up to date\n' "${show_date}" >&2
     printf '%s\n' "${directory}"
     exit 0
 fi
diff --git a/bin/phishin-like-show b/bin/phishin-like-show
--- a/bin/phishin-like-show
+++ b/bin/phishin-like-show
@@ -63,17 +63,17 @@ curl_authed() {
 
 [[ "$#" -gt 0 ]] || usage 'error: no arguments provided\n'
 
-for show; do
-    [[ "$show" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] \
-        || usage 'error: show argument is not an ISO format date: %s\n' "$show"
+for show_date; do
+    [[ "$show_date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] \
+        || usage 'error: show argument is not an ISO format date: %s\n' "$show_date"
 done
 
 phishin_auth
 
 errors=0
-for show; do
+for show_date; do
     # /likes requires the show ID be given, not a date
-    show_id=$(curl --fail-with-body "https://phish.in/api/v2/shows/${1?no show given}")
+    show_id=$(curl --fail-with-body "https://phish.in/api/v2/shows/${show_date}")
     show_id=$(jq -ce '.id' <<<"${show_id}")
 
     result=$(
@@ -82,11 +82,11 @@ for show; do
             | curl_authed -X POST --json @- "https://phish.in/api/v2/likes"
     )
 
-    if jq -cre --arg show "$show" '.id' <<<"$result" >/dev/null; then
-        printf '%s\n' "$show"
+    if jq -cre --arg show_date "$show_date" '.id' <<<"$result" >/dev/null; then
+        printf '%s\n' "$show_date"
     else
         errors=$((errors + 1))
-        printf 'error: failed while liking show %s (id: %i)\n' "$show" "$show_id" >&2
+        printf 'error: failed while liking show %s (id: %i)\n' "$show_date" "$show_id" >&2
     fi
 done
 
