phish-show-notes: don't run the whole archive thing if directory exists

diff --git a/bin/phish-download-show b/bin/phish-download-show
--- a/bin/phish-download-show
+++ b/bin/phish-download-show
@@ -158,69 +158,6 @@ near_show_data=$(
     fi
 )
 
-# Download the album, continuing an unfinished previous download if it exists.
-zip_raw="${zip%.zip}.raw.zip"
-if ! [[ -s "${zip_raw}" ]] && ! [[ -s "${zip}" ]]; then
-    # Fetch the ZIP from Phish.in, with progress, and continuing if
-    # an unfinished download exists.
-
-    edo curl \
-        --location \
-        --fail \
-        -# \
-        -o "${zip_raw}".part \
-        --continue-at - \
-        "${album_zip_url}" || exit 1
-
-    edo mv "${zip_raw}.part" "${zip_raw}"
-fi
-
-[[ "$only_download" == false ]] || exit
-
-# Take time to re-create the ZIP archive generated by Phish.in, and slip in a
-# phishin.json data file that contains the show data from the API while we're
-# at it.
-if [[ -s "$zip_raw" ]] && ! [[ -s "${zip}" ]]; then
-    repack=$(mktemp -d)
-    repack_album="${repack}/${filename}"
-    edo mkdir -p "$repack_album"
-
-    # This is done before extracting in hopes that maybe some day Phish.in
-    # will slip a phishin.json into the show archive itself.
-    printf '%s' "${phishin_show_data:?}" >"$repack_album"/phishin.json
-
-    # Extract the unedited archive into the album directory,
-    # and then remove the archive from the working directory.
-    edo bsdtar -C "$repack_album" -xf "${zip_raw}"
-
-    # Use a more default cover filename, and don't include the captionless
-    # version of the AI slop art.
-    edo rm -f "$repack_album"/cover_art.jpg
-    edo mv "$repack_album"/album_cover.jpg "$repack_album"/cover.jpg
-
-    # Repack it, with a leading subdirectory
-    edo bsdtar -C "$repack" -cf "${zip}".part "${filename}"/
-    edo mv "${zip}".part "${zip}"
-
-    edo rm -rf "$repack"
-fi
-
-[[ -e "$zip" ]] || exit 1
-
-edo rm -f "$zip_raw"
-
-if ! edo bsdtar -xf "${zip}"; then
-    printf 'error: failed while extracting downloaded album (%s)\n' "${zip@Q}" >&2
-    exit 1
-fi
-
-if ! [[ -d "${directory}" ]]; then
-    printf 'error: extracted archive, but %s does not exist\n' "${directory}" >&2
-    exit 1
-fi
-
-[[ "$keep_archive" == true ]] || edo rm -f "${zip}"
-
 # If the far and near show data differs (either $near_show_data is empty and
 # far is not or whatever) then we need to download the show again.
 # shellcheck disable=SC2312
@@ -234,6 +171,66 @@ then
     printf '%s\n' "${directory}"
     exit 0
 fi
+
+if ! [[ -d "${directory}" ]]; then
+    # Download the album, continuing an unfinished previous download if it exists.
+    zip_raw="${zip%.zip}.raw.zip"
+    if ! [[ -s "${zip_raw}" ]] && ! [[ -s "${zip}" ]]; then
+        # Fetch the ZIP from Phish.in, with progress, and continuing if
+        # an unfinished download exists.
+
+        edo curl \
+            --location \
+            --fail \
+            -# \
+            -o "${zip_raw}".part \
+            --continue-at - \
+            "${album_zip_url}" || exit 1
+
+        edo mv "${zip_raw}.part" "${zip_raw}"
+    fi
+
+    [[ "$only_download" == false ]] || exit
+
+    # Take time to re-create the ZIP archive generated by Phish.in, and slip in a
+    # phishin.json data file that contains the show data from the API while we're
+    # at it.
+    if [[ -s "$zip_raw" ]] && ! [[ -s "${zip}" ]]; then
+        repack=$(mktemp -d)
+        repack_album="${repack}/${filename}"
+        edo mkdir -p "$repack_album"
+
+        # This is done before extracting in hopes that maybe some day Phish.in
+        # will slip a phishin.json into the show archive itself.
+        printf '%s' "${phishin_show_data:?}" >"$repack_album"/phishin.json
+
+        # Extract the unedited archive into the album directory,
+        # and then remove the archive from the working directory.
+        edo bsdtar -C "$repack_album" -xf "${zip_raw}"
+
+        # Use a more default cover filename, and don't include the captionless
+        # version of the AI slop art.
+        edo rm -f "$repack_album"/cover_art.jpg
+        edo mv "$repack_album"/album_cover.jpg "$repack_album"/cover.jpg
+
+        # Repack it, with a leading subdirectory
+        edo bsdtar -C "$repack" -cf "${zip}".part "${filename}"/
+        edo mv "${zip}".part "${zip}"
+
+        edo rm -rf "$repack"
+    fi
+
+    [[ -e "$zip" ]] || exit 1
+
+    edo rm -f "$zip_raw"
+
+    if ! edo bsdtar -xf "${zip}"; then
+        printf 'error: failed while extracting downloaded album (%s)\n' "${zip@Q}" >&2
+        exit 1
+    fi
+fi
+
+[[ "$keep_archive" == true ]] || edo rm -f "${zip}"
 
 # Process the show data to get data pertaining to the track file in question,
 # and output it all in format suitable for `eval`.
